try seeing shape of responses

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -124,6 +124,7 @@ runs:
             -f "per_page=2" \
             -f "page=$page" \
           )
+          echo $res
 
           list=$(echo $res | jq -r '.[].tag_name')
 
@@ -139,6 +140,11 @@ runs:
             pattern = echo $regex | sed 's/\\d\+/\*/g' | sed 's/^.\(.*\).$/\1/'
 
             echo "Version ${{ github.event.release.name }} is unallowed. For this version to be valid, the previous version had to match the pattern $pattern, but no such version matching that pattern exists"
+            exit 1
+          fi
+
+          if [[ $page -gt 10 ]]; then
+            echo "Fatal error: more than 1000 releases, which is too many to check"
             exit 1
           fi
 
